### ISSUE TITLE
bug: 180 rows of data removed from air quality history

### ISSUE THREAD

**Issue by hydrosquall** [nychealth/realtime-air-quality#2]
Hi,

A few days ago, a large slice data was removed a few days ago after this commit, and the new rows don't contain any air quality readings.

https://github.com/nychealth/realtime-air-quality/commit/24dd44ff2ab0ae278e1360403c7e02348df03356

As a result, the graphs on the real-time page are empty: https://a816-dohbesp.nyc.gov/IndicatorPublic/AQHub/realtime.htm

![Image 2022-03-06 at 3 59 08 PM](https://user-images.githubusercontent.com/9020979/156941974-7f4ada82-327d-47a1-9c72-12e15b82097b.jpg)

Would it make sense to restore the old rows before continuing to run the append rows script?

**Comment by hydrosquall** [comment]
Update - it looks like the rows were added back here:

https://github.com/nychealth/realtime-air-quality/commit/328159a9056c276320669117d750e9866ff8f8c0

**Comment by mmontesanonyc** [comment]
Yup, we got that feed back up and running. Thanks for paying attention and filing the issue - we appreciate it.
